// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDltBX4UEr1cf7Q7LxGtUwfgHTuE629bOo',
    appId: '1:889674408504:web:1adcde2a4b6efe12377ccd',
    messagingSenderId: '889674408504',
    projectId: 'socialmediaapp-b981f',
    authDomain: 'socialmediaapp-b981f.firebaseapp.com',
    storageBucket: 'socialmediaapp-b981f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClpuOzhalP4nAxsC9SzWve5uQkkcdDRPk',
    appId: '1:889674408504:android:f8b13c84ee08d41c377ccd',
    messagingSenderId: '889674408504',
    projectId: 'socialmediaapp-b981f',
    storageBucket: 'socialmediaapp-b981f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDe0S9z_p8WQeK4xvzfnTKPp7lFzwjA_Sc',
    appId: '1:889674408504:ios:1bd9ecd7b52d146c377ccd',
    messagingSenderId: '889674408504',
    projectId: 'socialmediaapp-b981f',
    storageBucket: 'socialmediaapp-b981f.appspot.com',
    iosBundleId: 'com.example.untitled1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDe0S9z_p8WQeK4xvzfnTKPp7lFzwjA_Sc',
    appId: '1:889674408504:ios:639e4d5ed7e382a0377ccd',
    messagingSenderId: '889674408504',
    projectId: 'socialmediaapp-b981f',
    storageBucket: 'socialmediaapp-b981f.appspot.com',
    iosBundleId: 'com.example.untitled1.RunnerTests',
  );
}
